### ISSUE TITLE
cannot download unofficial dockerhub repos

### ISSUE THREAD

**Issue by tpdownes** [opensciencegrid/cvmfs-singularity-sync#11]
I am trying to use this script in my own workflow. I find that it works fine for official repos such as `centos:6` (etc) but not for ones in other namespaces. e.g. LIGO
```
thomas.downes@downes-dev:~/cvmfs-singularity-sync$ ./cvmfs-singularity-sync --docker ligo/ligo-wn:latest --rootfs /tmp/tpdownes/
Docker image to publish: ligo/ligo-wn:latest
Error getting tags using url https://registry-1.docker.io/v2/ligo/ligo-wn/tags/list
```
I do not believe this was always the case. It affects the bulk of the repos listed in `docker_images.txt` and the behavior is the same if I use the `images-url` argument instead.

I have also tried reverting to a version prior to glob support with the same outcome. I have even tried the `cli.py` file inside the singularity package. Same outcome.

Is this what it would look like if I have been blocked by Docker hub?

**Comment by bbockelm** [comment]
Now that we overhauled the guts of this script to use the local Docker daemon (having access to the full set of APIs), we should be able to do this, I think.

Adding Derek.

**Comment by tpdownes** [comment]
I tested my script against containers.ligo.org (even authenticated) successfully.

**Comment by jthiltges** [comment]
I believe this issue is resolved. We've since switched to apptainer (singularity) sandbox to generate images in #195.
