### ISSUE TITLE
CVMFS not syncing for drtmfigy/fbps

### ISSUE THREAD

**Issue by drtmfigy** [opensciencegrid/cvmfs-singularity-sync#116]
I have pushed a new Docker container to drtmfigy/fbps on the Docker hub.  However, 
the CVMFS has not been rebuilt on OSG.

**Comment by djw8605** [comment]
Hi,

I see that this image is now sync'd.  I am closing this issue, but feel free to reopen if you are not able to see the image as well.

-Derek
