### ISSUE TITLE
please delete ligo-wn image from CVMFS

### ISSUE THREAD

**Issue by tpdownes** [opensciencegrid/cvmfs-singularity-sync#26]
I'm filing a GitHub issue on the principle that this is easier to track than e-mail threads. I would like you to delete the following path and all its contents:
```
/cvmfs/singularity.opensciencegrid.org/ligo/ligo-wn:latest
```
It has been replaced by several tags under `ligo/software`. Let me know if you prefer this request to come other ways.

**Comment by bbockelm** [comment]
Working on this now.

**Comment by bbockelm** [comment]
Done.  Should propagate out to the CDN over the next 30 minutes or so.  Please reopen if you see any issues.
