### ISSUE TITLE
add atlas analysisbase image

### ISSUE THREAD

**Issue by lukasheinrich** [opensciencegrid/cvmfs-singularity-sync#34]
ATLAS is starting to build docker images of its analysis software and I wanted to test it via singularity

can you add `atlas/analysisbase:21.2.4` to the OSG cvmfs repo?

Thanks,
Lukas

**Comment by bbockelm** [comment]
Hi Lukas,

Can you please send a PR?  That's the easiest route!

Brian

**Comment by lukasheinrich** [comment]
done: https://github.com/opensciencegrid/cvmfs-singularity-sync/pull/35

**Comment by lukasheinrich** [comment]
when is the next sync?

**Comment by LincolnBryant** [comment]
FWIW- I see that the image seems to be there now. 

```
# ls /cvmfs/singularity.opensciencegrid.org/atlas/analysisbase:21.2.4
bin  cvmfs  dev  etc  home  lib  lib64  lost+found  media  mnt  opt  proc  root  sbin  selinux  srv  sys  tmp  usr  var
```

**Comment by bbockelm** [comment]
Closing, as this seems to be there.

@lukasheinrich - we just overhauled the guts of this script to use the official Docker API instead of the (internal) singularity python API.  Please watch for any follow-up issues -- but hopefully it should be for the better!
