### ISSUE TITLE
Multiarchitecture images: is amd64 guaranteed to be synced?

### ISSUE THREAD

**Issue by wdconinc** [opensciencegrid/cvmfs-singularity-sync#415]
We are exploring expanding to multiarchitecture images for some of our images that are synced to cvmfs. Does the infrastructure here guarantee that the amd64 image will continue to get synced to cvmfs, not the arm64 image, or is this untested behavior?

**Comment by djw8605** [comment]
I believe this is untested.  I'm not sure how the sync would handle this.

**Comment by wdconinc** [comment]
It seems `rocker/r-ver:latest` is a multiarchitecture image, https://hub.docker.com/layers/rocker/r-ver/latest/images/sha256-8ad0d6a1dd693e703d07cbf5591cf20cce4fe1cb1220080720afd3074a25db1b?context=explore, and it seems to have been synced, and the synced version is the amd64 architecture. So, maybe this 'just works' and defaults to amd64.

**Comment by jthiltges** [comment]
Dear Wouter,

We corresponded in the OSG ticket, but wanted to close things out here too.

We call apptainer (singularity) to build the sandbox image.
https://github.com/opensciencegrid/cvmfs-singularity-sync/blob/bc659ef2378b48577b4b54dd797363695e411adf/cvmfs-singularity-sync#L441-L447

I believe apptainer uses the native architecture to decide which image to retrieve. We don't have a roadmap toward supporting non-amd64 images at present.

Regarding the sync errors, to handle changes in docker hub manifests that were causing image validation errors, I'd updated the list of manifests we accept in #424.

This caused some unexpected breakage, as I didn't handle the new manifest format correctly. My apologies for the trouble. This should now be addressed in #427 and in production from April 20. Please let us know, and reopen the issue if necessary.

Regards,
John

**Comment by wdconinc** [comment]
It took me a couple of days to reenable the multi-platform builds, but the sync to cvmfs is indeed working again. Thanks a lot!

We don't aim to run non-amd64 images directly from cvmfs (instead we pull them directly from dockerhub and ghcr on those platform), so continuing to default to amd64 on cvmfs is perfectly fine with us.
